In [4]:
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


In [ ]:
num=np.array([i for i in range(1,21)])
print(num)
print("sum:",num.sum())
print("Standard deviation:",num.std())
print("Average:", num.sum()/len(num))
print("mean:",num.mean())


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
sum 210
Standard deviation 5.766281297335398
Average 10.5
mean 10.5


In [ ]:
matrix=np.array([[1,4,5],[4,6,7],[5,6,7]])
print(matrix)
row_sum=np.sum(matrix, axis=0)
print("ROW WISE SUM:", row_sum)


[[1 4 5]
 [4 6 7]
 [5 6 7]]
ROW WISE SUM: [10 17 18]
